### ISSUE TITLE
Kernel 4.15rc1 support?

### ISSUE THREAD

**Issue by oscarbg** [yzytom/gordboy-rtl8812au#1]

**Comment by yzytom** [comment]
I never tried it on kernel 4.15rc1,and you can try it.
rtl8812au works well with kernel 4.13 and earlier(except for kernel 4.10)

**Comment by oscarbg** [comment]
sorry for not being clear.. doesn't work already tested.. issues with new timers kernel..

**Comment by yzytom** [comment]
thanks for your feedback
